# Generated by Django 6.0.3 on 2026-03-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_pickup_date_pickuprequest_pickup_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickuprequest',
            old_name='pickup_date',
            new_name='pickup_Date',
        ),
    ]
