# Generated by Django 6.0.3 on 2026-04-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chatroom_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Chat/'),
        ),
        migrations.AddField(
            model_name='wastecategory',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
