# Generated by Django 6.0.3 on 2026-04-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatbox_image_wastecategory_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecategory',
            name='message',
        ),
    ]
