# Generated by Django 6.0.3 on 2026-04-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_wastecategory_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
