# Generated by Django 6.0.3 on 2026-05-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_chatbox_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pickup_images/'),
        ),
    ]
