# Generated by Django 6.0.3 on 2026-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pickuprequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='completion_proofs/'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='completion_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
