# Generated by Django 6.0.3 on 2026-05-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pickuprequest_completion_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='completion_image',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='completion_note',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
