# Generated by Django 6.0.3 on 2026-05-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notification_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
