# Generated by Django 6.0.3 on 2026-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclerassignment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recyclerassignment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recyclerassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
